apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
    {{- include "k8s-deployment-demo.commonLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}