apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/name: app-config
    {{- include "k8s-deployment-demo.commonLabels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.accessTokenExpireMinutes | quote }}
  CACHE_TTL_SECONDS: {{ .Values.config.cacheTtlSeconds | quote }}
  REDIS_URL: {{ .Values.config.redisUrl | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}