apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/name: app-config
    app.kubernetes.io/instance: k8s-deployment-demo
    app.kubernetes.io/part-of: k8s-deployment-demo
    app.kubernetes.io/managed-by: kubectl
data:
  LOG_LEVEL: "INFO"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  CACHE_TTL_SECONDS: "60"
  REDIS_URL: "redis://redis:6379/0"
  POSTGRES_USER: "app_user"
  POSTGRES_DB: "app_db"