apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: k8s-deployment-demo
    app.kubernetes.io/part-of: k8s-deployment-demo
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50